package com.microvecter.factVecter;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class factVecterMain {

    private Form current;
    private Resources theme;
    private final int CenterSize=4;
    private final BoxLayout boxLayout = new BoxLayout(BoxLayout.Y_AXIS);

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form homePage = new Form("FactVecter");
        homePage.setLayout(boxLayout);
        Stats objValid=new Stats();
           
        //homePage.addComponent(new Label("The button"));
        //homePage.show();
        Label lbname=new Label("Enter your name");
        homePage.add(lbname);
        
        TextField txtname=new TextField();
        homePage.add(txtname);
        
        Label idNumber=new Label("Enter your 5 ID last digits");
        homePage.add(idNumber);
        
        TextField txtIDnumber=new TextField();
        homePage.add(txtIDnumber);
        
        Label lbage=new Label("Select Date of Birth");
        homePage.add(lbage);
        
        Picker datePicker = new Picker();
        datePicker.setType(Display.PICKER_TYPE_DATE);
        datePicker.setAlignment(CenterSize);
        homePage.add(datePicker); 
        
        Button btn=new Button("show my stats");
        homePage.add(btn);
        
       btn.addActionListener(e -> objValid.validating(txtname.getText(),txtIDnumber.getText(),datePicker.getDate()));
       // testBtn.addActionListener(e -> objValid.TestMethod(datePicker.getDate()));
       //Button Test=new Button("Test Button");
       //homePage.add(Test);
       
      // Test.addActionListener(e -> objValid.TestMethod(datePicker.getDate()));
        
        /*Button dateTime=new Button("DateTime");
        homePage.add(dateTime);
        
       dateTime.addActionListener(e -> objValid.showDate());*/
        
       // Dialog dialog=new Dialog();
       //dialog.show("!!! Warning",data,"OK!!",null);
        
        //btn.addActionListener((e) -> Dialog.show("!!! Warning","Thanks for using Microvecter App","OK!!",null));

        homePage.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
